[package]
name = "comptime"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.82"
quote = "1.0.36"
syn = {version = "2.0.64", features = ["full"]}

[lib]
crate_type = ["proc-macro"]